/*******************************************/
/*     FILE GENERATED BY iec2c             */
/* Editing this file is not recommended... */
/*******************************************/

#include "iec_std_lib.h"

// RESOURCE RES

extern unsigned long long common_ticktime__;

#include "accessor.h"
#include "POUS.h"

#include "Config.h"

#include "POUS.c"

BOOL TASKMAIN;
SCENE1 RES__INST;
#define INST RES__INST

void RES_init__(void) {
  BOOL retain;
  retain = 0;
  
  TASKMAIN = __BOOL_LITERAL(FALSE);
  SCENE1_init__(&INST,retain);
}

void RES_run__(unsigned long tick) {
  TASKMAIN = !(tick % 1);
  if (TASKMAIN) {
    SCENE1_body__(&INST);
  }
}

