#ifndef __POUS_H
#define __POUS_H

#include "accessor.h"
#include "iec_std_lib.h"

// PROGRAM CELL1
// Data part
typedef struct {
  // PROGRAM Interface - IN, OUT, IN_OUT variables

  // PROGRAM private variables - TEMP, private and located variables
  __DECLARE_LOCATED(BOOL,R1_FRONT)
  __DECLARE_LOCATED(BOOL,R1_REAR)
  __DECLARE_LOCATED(BOOL,C1_ENDIR)
  __DECLARE_LOCATED(BOOL,C1_STARTIR)
  __DECLARE_LOCATED(BOOL,MAIN)
  __DECLARE_LOCATED(BOOL,R1_FWD_MOTOR)
  __DECLARE_LOCATED(BOOL,R1_BWD_MOTOR)
  __DECLARE_LOCATED(BOOL,C1_MOTOR)
  __DECLARE_VAR(BOOL,C1_WORKING)
  __DECLARE_LOCATED(DINT,C1_WORKING_INT)
  __DECLARE_VAR(BOOL,R1_IN_TRANSIT)
  __DECLARE_LOCATED(DINT,R1_IN_TRANSIT_INT)
  __DECLARE_VAR(BOOL,R1_FWD)
  __DECLARE_LOCATED(DINT,R1_FWD_INT)
  __DECLARE_VAR(BOOL,R1_BWD)
  __DECLARE_LOCATED(DINT,R1_BWD_INT)
  TON TIMER_IN_TRANSIT;
  __DECLARE_VAR(BOOL,BOOL_TO_DINT27_ENO)
  __DECLARE_VAR(DINT,BOOL_TO_DINT27_OUT)
  __DECLARE_VAR(BOOL,BOOL_TO_DINT37_ENO)
  __DECLARE_VAR(DINT,BOOL_TO_DINT37_OUT)
  __DECLARE_VAR(BOOL,BOOL_TO_DINT61_ENO)
  __DECLARE_VAR(DINT,BOOL_TO_DINT61_OUT)
  __DECLARE_VAR(BOOL,BOOL_TO_DINT67_ENO)
  __DECLARE_VAR(DINT,BOOL_TO_DINT67_OUT)

} CELL1;

void CELL1_init__(CELL1 *data__, BOOL retain);
// Code part
void CELL1_body__(CELL1 *data__);
#endif //__POUS_H
