#include "interface.h"

// NOTES this file will be autogenerated

// ===== Lengths of IEC_TYPE variables ===== //
const size_t inputs_lens[NUM_IEC_TYPES] = { 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
const size_t outputs_lens[NUM_IEC_TYPES] = { 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };

// ===== Functions ===== //
// TODO write the function code
void init_variables()
{
	// Initialize variables
	config_init__();

	// Initialize inputs/outputs
	inputs = (void***)malloc(NUM_IEC_TYPES * sizeof(void**));
	outputs = (void***)malloc(NUM_IEC_TYPES * sizeof(void**));

	size_t i;
	for (i = 0; i < NUM_IEC_TYPES; i++)
	{
		inputs[i] = (void**)malloc(inputs_lens[i] * sizeof(void*));
		outputs[i] = (void**)malloc(outputs_lens[i] * sizeof(void*));
	}

	// IEC_BOOL
        inputs[0][0] = (void*)__IX0_5; // C1_startIR
	inputs[0][1] = (void*)__IX0_4; // C1_endIR

	outputs[0][0] = (void*)__QX0_4; // C1_motor
        outputs[0][1] = (void*)__QX0_2; // R1_fwd_motor
}
