#ifndef __POUS_H
#define __POUS_H

#include "accessor.h"
#include "iec_std_lib.h"

// PROGRAM CELL4
// Data part
typedef struct {
  // PROGRAM Interface - IN, OUT, IN_OUT variables

  // PROGRAM private variables - TEMP, private and located variables
  __DECLARE_LOCATED(BOOL,R2_FRONT)
  __DECLARE_LOCATED(BOOL,R2_REAR)
  __DECLARE_LOCATED(BOOL,C4_ENDIR)
  __DECLARE_LOCATED(BOOL,C3_IR)
  __DECLARE_LOCATED(BOOL,MAIN)
  __DECLARE_LOCATED(BOOL,R2_FWD_MOTOR)
  __DECLARE_LOCATED(BOOL,R2_BWD_MOTOR)
  __DECLARE_LOCATED(BOOL,C4_MOTOR)
  __DECLARE_VAR(BOOL,C4_WORKING)
  __DECLARE_LOCATED(DINT,C4_WORKING_INT)
  __DECLARE_VAR(BOOL,R2_IN_TRANSIT)
  __DECLARE_LOCATED(DINT,R2_IN_TRANSIT_INT)
  __DECLARE_VAR(BOOL,R2_FWD)
  __DECLARE_LOCATED(DINT,R2_FWD_INT)
  __DECLARE_VAR(BOOL,R2_BWD)
  __DECLARE_LOCATED(DINT,R2_BWD_INT)
  TON TIMER_IN_TRANSIT;
  __DECLARE_VAR(BOOL,BOOL_TO_DINT49_ENO)
  __DECLARE_VAR(DINT,BOOL_TO_DINT49_OUT)
  __DECLARE_VAR(BOOL,BOOL_TO_DINT64_ENO)
  __DECLARE_VAR(DINT,BOOL_TO_DINT64_OUT)
  __DECLARE_VAR(BOOL,BOOL_TO_DINT61_ENO)
  __DECLARE_VAR(DINT,BOOL_TO_DINT61_OUT)
  __DECLARE_VAR(BOOL,BOOL_TO_DINT67_ENO)
  __DECLARE_VAR(DINT,BOOL_TO_DINT67_OUT)

} CELL4;

void CELL4_init__(CELL4 *data__, BOOL retain);
// Code part
void CELL4_body__(CELL4 *data__);
#endif //__POUS_H
